sonar.projectKey=merchant_portal_backend
sonar.projectName=merchant_portal_backend
sonar.projectVersion=1.0
sonar.language=ts
sonar.sourceEncoding=UTF-8
sonar.java.binaries=${WORKSPACE}/**/target
sonar.qualitygate=fc-quality-gate
sonar.profile=fc-quality-profile