vault.path=https://fcvault.fcinternal.in
vault.auth.uri=/v1/auth/ldap/login/

#databag path
vault.databag.prefix=databags/data/
vault.databag.secret.path=merchant/merchant_portal/application.properties
vault.db.secret.path = merchant/merchant_portal/db.properties
