# #databases paths
# vault.database.merchant_portal= prod_merchant_portal_prod_write
# vault.database.eil= prod_eilservice_prod_read
# vault.database.mob= prod_payments_mob_aurora_prod_read

vault.database.merchant_portal=staging_merchant_portal_write
vault.database.eil= qa_eil_qa_read
vault.database.mob= staging_payments_mob_staging_write